

export const tableType = {
    holiday_list : {
        name:'holiday_list',
        headers:[
        {
            key:'id',
            filterType:[],
            type:null
        },
        {
            key:'name',
            filterType:[{
                title:'iendswith',
                shortTitle:'ew'
            },
            {
                title:'istartswith',
                shortTitle:'sw'
            },
            {
                title:'icontains',
                shortTitle:'con'
            },
            {
                title:'iexact',
                shortTitle:'ext'
            }
        ],
            type:'string'
        },
        {
            key:'holiday_date',
            filterType:[],
            type:null
        },
        {
            key:'no_of_holiday',
            filterType:[
                {
                    title:'less_than',
                    shortTitle:'lt'
                },
                {
                    title:'less_than_equal',
                    shortTitle:'lte'
                },
                {
                    title:'greater_than',
                    shortTitle:'gt'
                },
                {
                    title:'iexact',
                    shortTitle:'ext'
                }
            ],
            type:'number'
        }
    ]
    },
    hr_employee_list : {
        name:'hr_employee_list',
        headers:[
            {
                key:'id',
                filterType:[],
                type:null
            },
            {
                key:'name',
                filterType:[{
                    title:'iendswith',
                    shortTitle:'ew'
                },
                {
                    title:'istartswith',
                    shortTitle:'sw'
                },
                {
                    title:'icontains',
                    shortTitle:'con'
                },
                {
                    title:'iexact',
                    shortTitle:'ext'
                }
            ],
                type:'string'
            },
            {
                key:'role',
                filterType:[{
                    title:'iendswith',
                    shortTitle:'ew'
                },
                {
                    title:'istartswith',
                    shortTitle:'sw'
                },
                {
                    title:'icontains',
                    shortTitle:'con'
                },
                {
                    title:'iexact',
                    shortTitle:'ext'
                }
            ],
                type:'string'
            },
            {
                key:'designation',
                filterType:[{
                    title:'iendswith',
                    shortTitle:'ew'
                },
                {
                    title:'istartswith',
                    shortTitle:'sw'
                },
                {
                    title:'icontains',
                    shortTitle:'con'
                },
                {
                    title:'iexact',
                    shortTitle:'ext'
                }
            ],
                type:'string'
            },
            {
                key:'email',
                filterType:[{
                    title:'iendswith',
                    shortTitle:'ew'
                },
                {
                    title:'istartswith',
                    shortTitle:'sw'
                },
                {
                    title:'icontains',
                    shortTitle:'con'
                },
                {
                    title:'iexact',
                    shortTitle:'ext'
                }
            ],
                type:'string'
            },
        ]
    },
    hr_compensation_list : {
        name:'hr_compensation_list',
        headers:[
            {
                key:'id',
                filterType:[
                    {
                        title:'less_than',
                        shortTitle:'lt'
                    },
                    {
                        title:'less_than_equal',
                        shortTitle:'lte'
                    },
                    {
                        title:'greater_than',
                        shortTitle:'gt'
                    },
                    {
                        title:'iexact',
                        shortTitle:'ext'
                    }
                ],
                type:'number'
            },
            {
                key:'employee',
                filterType:[{
                    title:'iendswith',
                    shortTitle:'ew'
                },
                {
                    title:'istartswith',
                    shortTitle:'sw'
                },
                {
                    title:'icontains',
                    shortTitle:'con'
                },
                {
                    title:'iexact',
                    shortTitle:'ext'
                }
            ],
                type:'string'
            },
            {
                key:'ctc',
                filterType:[
                    {
                        title:'less_than',
                        shortTitle:'lt'
                    },
                    {
                        title:'less_than_equal',
                        shortTitle:'lte'
                    },
                    {
                        title:'greater_than',
                        shortTitle:'gt'
                    },
                    {
                        title:'iexact',
                        shortTitle:'ext'
                    }
                ],
                type:'number'
            },
            {
                key:'basic',
                filterType:[
                    {
                        title:'less_than',
                        shortTitle:'lt'
                    },
                    {
                        title:'less_than_equal',
                        shortTitle:'lte'
                    },
                    {
                        title:'greater_than',
                        shortTitle:'gt'
                    },
                    {
                        title:'iexact',
                        shortTitle:'ext'
                    }
                ],
                type:'number'
            },
            {
                key:'hra',
                filterType:[
                    {
                        title:'less_than',
                        shortTitle:'lt'
                    },
                    {
                        title:'less_than_equal',
                        shortTitle:'lte'
                    },
                    {
                        title:'greater_than',
                        shortTitle:'gt'
                    },
                    {
                        title:'iexact',
                        shortTitle:'ext'
                    }
                ],
                type:'number'
            }
        ]
    },
    hr_project_list : {
        name:'hr_project_list',
        headers:[
            {
                key:'id',
                filterType:[],
                type:null
            },
            {
                key:'name',
                filterType:[{
                    title:'iendswith',
                    shortTitle:'ew'
                },
                {
                    title:'istartswith',
                    shortTitle:'sw'
                },
                {
                    title:'icontains',
                    shortTitle:'con'
                },
                {
                    title:'iexact',
                    shortTitle:'ext'
                }
            ],
                type:'string'
            },
            {
                key:'employees',
                filterType:[],
                type:null
            },
        ]
    },
    onBoarding_list : {
        name:"onBoarding_list",
        headers:[
            {
                key:'id',
                filterType:[],
                type:null
            },
            {
                key:'name',
                filterType:[{
                    title:'iendswith',
                    shortTitle:'ew'
                },
                {
                    title:'istartswith',
                    shortTitle:'sw'
                },
                {
                    title:'icontains',
                    shortTitle:'con'
                },
                {
                    title:'iexact',
                    shortTitle:'ext'
                }
            ],
                type:'string'
            },
            {
                key:'role',
                filterType:[{
                    title:'iendswith',
                    shortTitle:'ew'
                },
                {
                    title:'istartswith',
                    shortTitle:'sw'
                },
                {
                    title:'icontains',
                    shortTitle:'con'
                },
                {
                    title:'iexact',
                    shortTitle:'ext'
                }
            ],
                type:'string'
            },
            {
                key:'designation',
                filterType:[{
                    title:'iendswith',
                    shortTitle:'ew'
                },
                {
                    title:'istartswith',
                    shortTitle:'sw'
                },
                {
                    title:'icontains',
                    shortTitle:'con'
                },
                {
                    title:'iexact',
                    shortTitle:'ext'
                }
            ],
                type:'string'
            },
            {
                key:'email',
                filterType:[{
                    title:'iendswith',
                    shortTitle:'ew'
                },
                {
                    title:'istartswith',
                    shortTitle:'sw'
                },
                {
                    title:'icontains',
                    shortTitle:'con'
                },
                {
                    title:'iexact',
                    shortTitle:'ext'
                }
            ],
                type:'email'
            },
        ]
    },
    compensation_on_details : {
        name:'compensation_on_details',
        headers:[
            {
                key:'id',
                filterType:[],
                type:null
            },
            {
                key:'ctc',
                filterType:[],
                type:null
            },
            {
                key:'basic',
                filterType:[],
                type:null
            },
            {
                key:'hra',
                filterType:[],
                type:null
            },
        ]
    },
    project_list : {
        name:'project_list',
        headers:[
            {
                key:'id',
                filterType:[],
                type:null
            },
            {
                key:'name',
                filterType:[{
                    title:'iendswith',
                    shortTitle:'ew'
                },
                {
                    title:'istartswith',
                    shortTitle:'sw'
                },
                {
                    title:'icontains',
                    shortTitle:'con'
                },
                {
                    title:'iexact',
                    shortTitle:'ext'
                }
            ],
                type:'string'
            },
        ]
    },
    manager_employee_list : {
        name:'manager_employee_list',
        headers:[
            {
                key:'id',
                filterType:[],
                type:null
            },
            {
                key:'name',
                filterType:[{
                    title:'iendswith',
                    shortTitle:'ew'
                },
                {
                    title:'istartswith',
                    shortTitle:'sw'
                },
                {
                    title:'icontains',
                    shortTitle:'con'
                },
                {
                    title:'iexact',
                    shortTitle:'ext'
                }
            ],
                type:'string'
            },
            {
                key:'designation',
                filterType:[{
                    title:'iendswith',
                    shortTitle:'ew'
                },
                {
                    title:'istartswith',
                    shortTitle:'sw'
                },
                {
                    title:'icontains',
                    shortTitle:'con'
                },
                {
                    title:'iexact',
                    shortTitle:'ext'
                }
            ],
                type:'string'
            },
            {
                key:'email',
                filterType:[{
                    title:'iendswith',
                    shortTitle:'ew'
                },
                {
                    title:'istartswith',
                    shortTitle:'sw'
                },
                {
                    title:'icontains',
                    shortTitle:'con'
                },
                {
                    title:'iexact',
                    shortTitle:'ext'
                }
            ],
                type:'email'
            },
            {
                key:'isActive',
                filterType:[],
                type:null
            },
            {
                key:'createdAt',
                filterType:[],
                type:null
            },
        ]
    },
    client_list : {
        name:'client_list',
        headers:[
            {
                key:'id',
                filterType:[],
                type:null
            },
            {
                key:'name',
                filterType:[{
                    title:'iendswith',
                    shortTitle:'ew'
                },
                {
                    title:'istartswith',
                    shortTitle:'sw'
                },
                {
                    title:'icontains',
                    shortTitle:'con'
                },
                {
                    title:'iexact',
                    shortTitle:'ext'
                }
            ],
                type:'string'
            },
        ]
    }
}

